[tool.poetry]
name = "infusoria"
version = "0.1.0"
description = "App to work with images taken under a microscope"
authors = ["dmcooller"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pyside6 = "6.8.1"
opencv-python-headless = "^4.10.0.84"
numpy = "^1.26.4"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
isort = "^5.13.2"
mypy = "^1.9.0"
pylint = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
enable = [
    'all'
]
disable = [
    'import-error',
    'no-name-in-module',
    'missing-function-docstring',
    'missing-module-docstring',
    'missing-class-docstring',
    'C0103',
]
